-- MySQL Script generated by MySQL Workbench
-- Mon May  9 16:14:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loyolaBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loyolaBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loyolaBD` DEFAULT CHARACTER SET utf8 ;
USE `loyolaBD` ;

-- -----------------------------------------------------
-- Table `loyolaBD`.`calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`calendario` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`calendario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `activo` TINYINT NULL DEFAULT NULL,
  `rol_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calendario_color1_idx` (`color` ASC) VISIBLE)
ENGINE = INNODB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`disponibilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`disponibilidad` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`disponibilidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `disponible` VARCHAR(45) NULL DEFAULT NULL,
  `hecho` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`estado` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`estado` (
  `id` INT NOT NULL,
  `estado` VARCHAR(92) NOT NULL,
  `pais_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`etapas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`etapas` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`etapas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `etapa` VARCHAR(45) NULL DEFAULT NULL,
  `porcentaje` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`notificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`notificaciones` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`notificaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`pais` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `codigo_postal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
AUTO_INCREMENT = 245
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`roles` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`usuario` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(125) CHARACTER SET 'ascii' NOT NULL,
  `apellido` VARCHAR(125) NOT NULL,
  `pass` VARCHAR(90) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_modificacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `v_luz` VARCHAR(255) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `roles_id` INT NULL,
  `pais_id` INT NULL,
  `disponibilidad_id` INT NULL,
  `papa` INT NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`usuario_historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`usuario_historial` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`usuario_historial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(125) CHARACTER SET 'ascii' NOT NULL,
  `apellido` VARCHAR(125) NOT NULL,
  `pass` VARCHAR(90) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `papa` INT NULL DEFAULT NULL,
  `estado_id` INT NULL DEFAULT NULL,
  `roles_id` INT NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  `fecha_modificacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `v_luz` FLOAT NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `modifica_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_estado1_idx` (`estado_id` ASC) VISIBLE,
  INDEX `fk_usuario_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_usuario_usuario1_idx` (`papa` ASC) VISIBLE,
  INDEX `fk_usuario_modifica10` (`modifica_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_estado10`
    FOREIGN KEY (`estado_id`)
    REFERENCES `loyolaBD`.`estado` (`id`),
  CONSTRAINT `fk_usuario_modifica10`
    FOREIGN KEY (`modifica_usuario`)
    REFERENCES `loyolaBD`.`usuario` (`id`),
  CONSTRAINT `fk_usuario_roles10`
    FOREIGN KEY (`roles_id`)
    REFERENCES `loyolaBD`.`roles` (`id`),
  CONSTRAINT `fk_usuario_usuario10`
    FOREIGN KEY (`papa`)
    REFERENCES `loyolaBD`.`usuario` (`id`))
ENGINE = INNODB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`venta` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `etapas_id` INT NULL,
  `disponibilidad_id` INT NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `loyolaBD`.`venta_historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolaBD`.`venta_historial` ;

CREATE TABLE IF NOT EXISTS `loyolaBD`.`venta_historial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_actualiza` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `etapas_id` INT NULL,
  `disponibilidad_id` INT NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb3;

USE `loyolaBD`;

DELIMITER $$

USE `loyolaBD`$$
DROP TRIGGER IF EXISTS `loyolaBD`.`venta_BEFORE_UPDATE` $$
USE `loyolaBD`$$
/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `venta_BEFORE_UPDATE` BEFORE UPDATE ON `venta` FOR EACH ROW BEGIN

END */$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
